Repository cucumber/vscode, pull requests merged in 2023-12, with the labels that each got.

#161 Migrate from deprecated VSCode dependencies
  package-lock.json
  package.json
  src/test/runTest.ts
Labels: :robot: dependencies

#193 Improve contributing guidelines
  ..HEAD
  .vscode/settings.json
  .vscodeignore
  CONTRIBUTING.md
  README.md
  RELEASING.md
  package.json
  vsc-extension-quickstart.md
Labels: :book: documentation

#144 Fix glue for csharp steps
  CHANGELOG.md
  README.md
  package.json
Labels: c_sharp

#195 Optimise bundling to reduce extension size
  .vscodeignore
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  images/icon-128x128.png
  images/icon.png
  images/vscode-output.png
  package.json
Labels: :bank: debt

#197 Document multi-root workspace usage
  README.md
Labels: :book: documentation

#196 Remove unused gherkin grammar for syntax highlight
  syntaxes/gherkin-classic.tmLanguage
Labels: :bank: debt

#198 Document gherkin localisation configuration
  README.md
  images/localisation.png
Labels: :book: documentation

#199 Document modifying language server
  .vscode/.gitignore
  CONTRIBUTING.md
  README.md
  package.json
Labels: :book: documentation
